import { useEffect, useState } from "react";
import type { Model } from "../../types";
import { fetchSkills } from "../../api";
import PageShell, { card, Empty } from "./PageShell";

export default function CapabilitiesPage({ models, connected }: { models: Model[]; connected: boolean }) {
  const [skills, setSkills] = useState<{ name: string; desc: string }[]>([]);

  useEffect(() => { if (connected) fetchSkills().then(setSkills); }, [connected]);

  return (
    <PageShell title="Capabilities" hint="What this local backend can use right now.">
      <h2 style={{ fontSize: 13, color: "var(--text-dim)", margin: "8px 0", textTransform: "uppercase", letterSpacing: "0.08em" }}>Models</h2>
      {models.length === 0 && <Empty text="No models found. Put .gguf files in the models folder." />}
      {models.map(m => <div key={m.name} style={card}>{m.name}</div>)}
      <h2 style={{ fontSize: 13, color: "var(--text-dim)", margin: "20px 0 8px", textTransform: "uppercase", letterSpacing: "0.08em" }}>Skills</h2>
      {skills.length === 0 && <Empty text="No skills yet. Skills are generated by the backend and saved in the skills folder." />}
      {skills.map(s => (
        <div key={s.name} style={card}>
          <div style={{ fontWeight: 600, fontSize: 13 }}>{s.name}</div>
          {s.desc && <div style={{ color: "var(--text-dim)", fontSize: 12, marginTop: 2 }}>{s.desc}</div>}
        </div>
      ))}
    </PageShell>
  );
}
